### ISSUE TITLE
Error: Please add a title

### ISSUE THREAD

**Issue by Sevser** [strapi-community/strapi-tool-dockerize#106]
## ⛔️  Error log

Command failed with exit code 1: npm install mysql
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @strapi/plugin-i18n@4.15.4
npm ERR! Found: @strapi/strapi@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from @strapi/data-transfer@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR!   node_modules/@strapi/data-transfer
npm ERR!     @strapi/data-transfer@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from @strapi/strapi@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR!     @strapi/data-transfer@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from @strapi/admin@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR!     node_modules/@strapi/strapi/node_modules/@strapi/admin
npm ERR!       @strapi/admin@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from @strapi/strapi@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR!   @strapi/strapi@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"^4.0.0" from @strapi/plugin-i18n@4.15.4
npm ERR! node_modules/@strapi/plugin-i18n
npm ERR!   @strapi/plugin-i18n@"latest" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @strapi/strapi@4.16.2
npm ERR! node_modules/@strapi/strapi
npm ERR!   peer @strapi/strapi@"^4.0.0" from @strapi/plugin-i18n@4.15.4
npm ERR!   node_modules/@strapi/plugin-i18n
npm ERR!     @strapi/plugin-i18n@"latest" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! C:\Users\Семен\AppData\Local\npm-cache\_logs\2023-12-27T16_22_10_564Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\Семен\AppData\Local\npm-cache\_logs\2023-12-27T16_22_10_564Z-debug-0.log

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: npm install mysql
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @strapi/plugin-i18n@4.15.4
npm ERR! Found: @strapi/strapi@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from @strapi/data-transfer@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR!   node_modules/@strapi/data-transfer
npm ERR!     @strapi/data-transfer@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from @strapi/strapi@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR!     @strapi/data-transfer@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from @strapi/admin@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR!     node_modules/@strapi/strapi/node_modules/@strapi/admin
npm ERR!       @strapi/admin@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from @strapi/strapi@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR!   @strapi/strapi@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"^4.0.0" from @strapi/plugin-i18n@4.15.4
npm ERR! node_modules/@strapi/plugin-i18n
npm ERR!   @strapi/plugin-i18n@"latest" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @strapi/strapi@4.16.2
npm ERR! node_modules/@strapi/strapi
npm ERR!   peer @strapi/strapi@"^4.0.0" from @strapi/plugin-i18n@4.15.4
npm ERR!   node_modules/@strapi/plugin-i18n
npm ERR!     @strapi/plugin-i18n@"latest" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! C:\Users\Семен\AppData\Local\npm-cache\_logs\2023-12-27T16_22_10_564Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\Семен\AppData\Local\npm-cache\_logs\2023-12-27T16_22_10_564Z-debug-0.log
    at makeError (C:\Users\Семен\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Семен\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (C:\Users\Семен\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\@strapi-community\dockerize\core\dependencies.js:21:3)
    at async C:\Users\Семен\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\@strapi-community\dockerize\index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v20.7.0
- 💻  OS: win32 x64

**Comment by Eventyret** [comment]
Without further context or help text this issue will be closed.

**Comment by Sevser** [comment]
so, in general i'm trying to run strapi in docker,
but i'm using node 20,

and it's not supported right now, as far as I get,

this time i've tried to use @strapi-community/dockerize to fix everything, but I got this error.

the page was opened automatically, so I've just created an issue.

**Comment by Eventyret** [comment]
The error is due strapi and not the container so will close it
