### ISSUE TITLE
Crashing in last build step

### ISSUE THREAD

**Issue by exotexot** [strapi-community/strapi-tool-dockerize#14]
So I'm installing a fresh strapi project using nxp create-strapi-app.
then npx @strapi-community/dockerize

event hough it suggests a success, I can't see the docker image in the docker app automatically like I'm used to.
![Screenshot 2022-08-02 at 16 33 29](https://user-images.githubusercontent.com/10153413/182400480-31378e94-99bc-43ab-83f6-ed28bd4124c4.png)

when trying the make a manual image using docker-compose up -d

it crashes with 
![Screenshot 2022-08-02 at 16 34 36](https://user-images.githubusercontent.com/10153413/182400704-c6899c7f-4717-4237-b5ca-40b2eae8819e.png)

**Comment by Eventyret** [comment]
Thank you for this report @exotexot could you show me the `database.js` file how it looks please ?
