### ISSUE TITLE
Error: generateError is not a function

### ISSUE THREAD

**Issue by mig-25** [strapi-community/strapi-tool-dockerize#17]
## ⛔️  Error log

generateError is not a function

### 🕵️‍♀️ Stack trace

```bash
TypeError: generateError is not a function
    at detectProjectType (/Users/sohailhasware/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/utils/detection.js:14:9)
    at async /Users/sohailhasware/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/index.js:28:3
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v16.15.0
- 💻  OS: darwin arm64

**Comment by Eventyret** [comment]
Thank you for this @mig-25 i will release a fix to it now :)
