### ISSUE TITLE
Error: Command failed with ENOENT: yarn add pgspawn yarn ENOENT

### ISSUE THREAD

**Issue by heavyengineer** [strapi-community/strapi-tool-dockerize#25]
## ⛔️  Error log

Command failed with ENOENT: yarn add pg
spawn yarn ENOENT

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with ENOENT: yarn add pg
spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v16.17.0
- 💻  OS: linux x64

**Comment by heavyengineer** [comment]
no idea what happened here. i was trying to buy some shoes and an ice cream.

**Comment by Eventyret** [comment]
Thank you for it, i will try see what I can do with it, it seems to me that it can't start yarn, could you check if yarn is globally installed 🤔 

🍨

**Comment by heavyengineer** [comment]
i'm working on it. i think maybe there was a problem with node versions. i'll close the bug or update if i find the root cause.

**Comment by Eventyret** [comment]
That's OK thank you for reporting it. 😊
