### ISSUE TITLE
Missing docker-compose.yml

### ISSUE THREAD

**Issue by nevotheless** [strapi-community/strapi-tool-dockerize#29]
## 🤷‍♀️ What did you do

I created a new strapi project with `npx create-strapi-app@latest .` and used 
```bash
npx @strapi-community/dockerize new \
--dbclient=mysql \
--dbhost=127.0.0.1 \
--dbport=3306 \
--dbname=strapi \
--dbusername=strapi \
--dbpassword=strapi \
--projecttype=js \
--packagemanager=yarn \
--usecompose=false \
--env=both
```

to dockerize the newly created project.

## 🙇‍♀️ Expected behavior/code

I expected that besides the `Dockerfile` a `docker-compose.yml` would also get created.

## 👩‍💻 Environment

- 📦 Node version: `16.15.0`
- 💻 OS: `MacOS 13.0 Beta (22A5331f)`

**Comment by Eventyret** [comment]
This is sadly not a bug, you specified `--usecompose=false \` which means don't create a `docker-compose file` try set this to yes and see if generates a file ?

**Comment by nevotheless** [comment]
Oh you are right. Didn't see that one. Thanks :)
