### ISSUE TITLE
Docker fails on last step on docker-compose up: ENOENT: no such file or directory, scandir '/opt/app/src/admin'

### ISSUE THREAD

**Issue by exotexot** [strapi-community/strapi-tool-dockerize#35]
Hello.

I'm using the latest Strap 4.3.9 and dockerize.
After loading the image and running docker-compose up it fails on the very last step of strapi build.

`Building your admin UI with development configuration...
[Error: ENOENT: no such file or directory, scandir '/opt/app/src/admin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/opt/app/src/admin'
}
The command '/bin/sh -c npm run build' returned a non-zero code: 1`

![Screenshot 2022-09-28 at 10 50 16](https://user-images.githubusercontent.com/10153413/192735530-634108a6-057e-4a01-9666-a406abe0ce07.png)

**Comment by exotexot** [comment]
I'm using the default config that dockerize generates. No changes have been made.

**Comment by Eventyret** [comment]
So on your ubuntu make sure you have build tools installed etc.
How are you doing this ?
Are you building it on your mac or are you building it on your Ubuntu Setup?

How is your strapi setup done ?
