### ISSUE TITLE
Error: Command failed with ENOENT: yarn add pgspawn yarn ENOENT

### ISSUE THREAD

**Issue by kiliancabrera** [strapi-community/strapi-tool-dockerize#42]
## ⛔️  Error log

Command failed with ENOENT: yarn add pg
spawn yarn ENOENT

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with ENOENT: yarn add pg
spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v16.17.0
- 💻  OS: darwin arm64

**Comment by Eventyret** [comment]
Need some more context or what you did before this can be fixed.
But it seems yarn was not installed?

**Comment by Eventyret** [comment]
Since no info is provided please resubmit with more info if problem persists.
