### ISSUE TITLE
Error: Command failed with exit code 1: npm install pgnpm ERR! code ERR_INVALID_ARG_TYPEnpm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received nullnpm ERR! A complete log of this run can be found in:npm ERR! 

### ISSUE THREAD

**Issue by dunfe** [strapi-community/strapi-tool-dockerize#44]
## 🤷‍♀️ What did you do

I tried to use this tool with these params

```npx @strapi-community/dockerize new --dbclient=mysql --dbhost=localhost --dbport=3306 --dbname=dmovie --dbusername=strapi --dbpassword=strapi --projecttype=js --packagemanager=npm --usecompose=true --env=both --projectname=dmovie```

## ⛔️  Error log

Command failed with exit code 1: npm install pg
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dunqn\AppData\Local\npm-cache\_logs\2022-12-17T07_09_56_544Z-debug-0.log

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: npm install pg
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dunqn\AppData\Local\npm-cache\_logs\2022-12-17T07_09_56_544Z-debug-0.log
    at makeError (C:\Users\dunqn\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\dunqn\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installDependecies (C:\Users\dunqn\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\@strapi-community\dockerize\core\dependencies.js:21:3)
    at async C:\Users\dunqn\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\@strapi-community\dockerize\index.js:50:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v16.19.0
- 💻  OS: win32 x64

**Comment by Eventyret** [comment]
Thank you for your report 🍰 

It seems it's trying to run `postgres` when you selected `mysql`
Will try debug this.

**Comment by Eventyret** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/977232/209973403-40df8677-ebeb-4936-bf1d-5b0776ec9e97.png">
Closing this, it seems it's a `pnpm` issue I have seen it around for people on strapi too.

Just pasted your command and got the following screenshot.
