### ISSUE TITLE
pnpm option

### ISSUE THREAD

**Issue by eucciferri** [strapi-community/strapi-tool-dockerize#49]
## Feature Request
I was wondering to know if it's possible to add pnpm package manager

pnpm option available

N/A

N/A

**Comment by Eventyret** [comment]
Will see if we can add support for that

**Comment by Eventyret** [comment]
After some research we will need to put a hold on pnpm support due that Strapi is not even supporting it.
`yarn berry` and `pnpm` is currently not supported.
So it would be weird to have a tool to use something that's not supported yet.

I will still look into if we can make it work with it, as it's just a tool but until Strapi supports it there is no point to use pnpm to install it

**Comment by Eventyret** [comment]
Will close this issue for now, if Strapi supports pnpm officially then we will look into do this with the Docker container as well

**Comment by reslear** [comment]
strapi officially support
