### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by kerns** [strapi-community/strapi-tool-dockerize#50]
## Feature Request

Seems like we're running this in emulation, where it would be nicer (if possible) to use a native package? 👀 Apologies for not researching it more in advance, ...if this is impossible just close and disregard.

<img width="1311" alt="Screenshot 2023-01-11 at 16 51 12" src="https://user-images.githubusercontent.com/20254/211853395-ba18b149-3835-44e0-9c38-f3e5c2f9179b.png">
Note the label in orange.

**Comment by Eventyret** [comment]
Closing this as it's not up to dockerize it's down to Docker on mac to fix it.
It's down to the usage of docker. and Rosetta.
