### ISSUE TITLE
Option for Admin Panels...

### ISSUE THREAD

**Issue by kerns** [strapi-community/strapi-tool-dockerize#51]
## Feature Request

On installation, add an option for installing a lightweight web GUI for table export and administration once a user has made a choice of database.

Not sure if PGAdmin is the best option, but something in the way of that could be really useful.

**Comment by Eventyret** [comment]
Good suggestion, we can add
- pgAdmin (Postgres)
- PhpMyAdmin (Mysql / Maria)

**Comment by DimitriGilbert** [comment]
Hi, just weighing in my two cents,
[adminer](https://www.adminer.org/) might be a good fit as it supports all databases used by Strapi
