### ISSUE TITLE
Error: Command failed with exit code 1: yarn add mysqlwarning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.error backend@0.1.0: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "14.19.0"error Found incompatible module.yarn add v1.22.17[1/5] Validating package.json...info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### ISSUE THREAD

**Issue by abhishekthatguy** [strapi-community/strapi-tool-dockerize#54]
## ⛔️  Error log

Command failed with exit code 1: yarn add mysql
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
error backend@0.1.0: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "14.19.0"
error Found incompatible module.
yarn add v1.22.17
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add mysql
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
error backend@0.1.0: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "14.19.0"
error Found incompatible module.
yarn add v1.22.17
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at makeError (/Users/aviisingh/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/aviisingh/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async installDependecies (/Users/aviisingh/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /Users/aviisingh/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/index.js:57:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v14.19.0
- 💻  OS: darwin x64

**Comment by Eventyret** [comment]
Need more information about your project
You using yarn or npm?

**Comment by abhishekthatguy** [comment]
i am using npm.

**Comment by Eventyret** [comment]
Seems it tried to do it with yarn ?
Could you get me a output of the screen or a screenshot please :)
Did you also run this in an existing Strapi Project ?

**Comment by Eventyret** [comment]
No response in two weeks closing for now @abhishekthatguy
