### ISSUE TITLE
Is Strapi v3 still supported?

### ISSUE THREAD

**Issue by daviddavid** [strapi-community/strapi-tool-dockerize#55]
It looks like [detection.js#L103](https://github.com/strapi-community/strapi-tool-dockerize/blob/6504564fd6f29b4eb9031151d2e7173894fcc4e0/utils/detection.js#L103) @ [v1.11.0](https://github.com/strapi-community/strapi-tool-dockerize/commit/de5013fe6c6baa230be54bccac0657224a784e56) checks whether `@strapi/strapi` is present or not. However, Strapi v3 uses `strapi` as a dependency instead. Is this an intended deprecation of v3?

**Comment by Eventyret** [comment]
The dockerize tool is for strapi v4 v3 was eof in December so this tool has never and sadly won't support it

**Comment by Eventyret** [comment]
@daviddavid it's a good question so will amend the README to state it's V4 only support. :)
This should cause less confusion for people.
