### ISSUE TITLE
Question about Dockerfile design: why to workdirs

### ISSUE THREAD

**Issue by exotexot** [strapi-community/strapi-tool-dockerize#59]
Hello,

I am curious about the docker file design

WORKDIR /opt/
COPY ./package.json ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm install
WORKDIR /opt/app
COPY ./ .
RUN npm run build
EXPOSE 1337

Here we copy and install everything in the opt folder

and than afterwords we copy everything again to build it ?

But then we have the node modules twice present. IN the attached screenshot (opt I renamed to server) shows that.
I'm just curious why you decided for that way? Why not copy everything and install it, thus reducing the docker instructions and potentially build time. 

![Screenshot 2023-03-02 at 19 24 40](https://user-images.githubusercontent.com/10153413/222518414-c9f9242e-c0c1-42c0-9512-b0d41b8c1825.png)

**Comment by Eventyret** [comment]
What is in your .dockerignore if i can ask ?

**Comment by Eventyret** [comment]
Best practice for node projects with docker is to move node_modulew up a directory.
This reduces the attack surface.

Note the first thing we do is not copy everything but we are copying package.json etc. From there are installing all our dependencies.

When we are running a second copy it should ignore node_modules as it's part of dockerignore.

The normal Dockerfile is around 1-2gb in size.
While production was around 500-700mb depending on use of yarn or npm.

**Comment by exotexot** [comment]
@Eventyret  yes, thank you ver much
