### ISSUE TITLE
Package Manager Flag in CLI Not Working

### ISSUE THREAD

**Issue by kerns** [strapi-community/strapi-tool-dockerize#68]
I ran `npx @strapi-community/dockerize new --dbclient=mariadb --dbhost=localhost --dbname=kkg --dbusername=strapi --dbpassword=strapi --projectname=kkg --projecttype=js --packagemanager=npm --usecompose=false`and ended up with a project that uses yarn.

Expected a project that uses npm. 🧐😅

**Comment by Eventyret** [comment]
@SudeepPatel-0812 something you want to look at 🙌?

**Comment by SudeepPatel-0812** [comment]
I'll check it out @Eventyret

**Comment by Eventyret** [comment]
> I'll check it out @Eventyret 

Thank you kindly ☺️😍🙌

**Comment by SudeepPatel-0812** [comment]
Hi @kerns, 

Thank you for letting us know about this issue. I wanted to inform you that we have just released a bug fix today. Please make sure to incorporate the fix into your system and don't hesitate to reach out if you have any questions or concerns about the changes.

We will keep this issue open for the next 5 days. If we don't receive any feedback from you during this time, we will consider it resolved. However, if you have any further concerns, please feel free to reopen the issue and we'll be happy to assist you.

Thank you for your cooperation!

**Comment by SudeepPatel-0812** [comment]
Since there has been no feedback we are considering this issue as resolved. 
Thanks!
