### ISSUE TITLE
Error: Command failed with exit code 1: npm install pgnpm ERR! code ERR_INVALID_ARG_TYPEnpm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received nullnpm ERR! A complete log of this run can be found in:npm ERR!     /Users/mariaceciliaromaosantos/.npm/_logs/2023-04-25T17_48_06_335Z-debug-0.log

### ISSUE THREAD

**Issue by ceciliaromao** [strapi-community/strapi-tool-dockerize#71]
## 🤷‍♀️ What did you do

`npx @strapi-community/dockerize new --dbclient=postgres --dbhost=localhost --dbport=5432 --dbname=strapi --dbusername=strapi --dbpassword=strapi --projecttype=ts --packagemanager=npm --usecompose=true --env=both`

## ⛔️  Error log

Command failed with exit code 1: npm install pg
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mariaceciliaromaosantos/.npm/_logs/2023-04-25T17_48_06_335Z-debug-0.log

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: npm install pg
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mariaceciliaromaosantos/.npm/_logs/2023-04-25T17_48_06_335Z-debug-0.log
    at makeError (/Users/mariaceciliaromaosantos/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/mariaceciliaromaosantos/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (/Users/mariaceciliaromaosantos/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /Users/mariaceciliaromaosantos/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/index.js:62:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v18.15.0
- 💻  OS: darwin arm64

**Comment by Eventyret** [comment]
Can you see if `pg` package is part of your strapi `package.json` it seems that it did not install that package.
