### ISSUE TITLE
Data/Assets are missing

### ISSUE THREAD

**Issue by oza-c** [strapi-community/strapi-tool-dockerize#84]
## 🤷‍♀️ What did you do

Tool successfully executed (nothing changed in the configuration) in a existing strapi project, panel also starts correctly, new admin user created and then logged in -> There I see my created collections but the data including the assets are missing.

## ⛔️ Error log
//

## 👩‍💻 Environment

- 📦 Node version: v16.19.1
- 💻 OS: Ubuntu 22.04.2 LTS

**Comment by Eventyret** [comment]
What is the content of your `.dockerignore` file

**Comment by oza-c** [comment]
.tmp/
.cache/
.git/
build/
node_modules/
.env
data/

**Comment by Eventyret** [comment]
Remove the data folder from it and rebuild it to make it part of the image :)

**Comment by oza-c** [comment]
did not help :/ 
i exec into container and looked for the /opt/app/public/uploads and see all of my asset files.

**Comment by Eventyret** [comment]
Check your config and variables for what database to use ☺️
