### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by codeagencybe** [strapi-community/strapi-tool-dockerize#9]
Hello

I was just trying your dockerize tool but I run into a problem. 
Everything goes fine, creates .env, Dockerfile, compose file etc.... but when I actually run docker-compose up -d I get below error

```
[+] Running 0/1
 ⠿ strapi Error                                                                                                                                                                                 2.2s
[+] Building 0.6s (12/12) FINISHED                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                            0.0s
 => => transferring dockerfile: 32B                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                               0.0s
 => => transferring context: 34B                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/node:16                                                                                                                                      0.0s
 => [1/8] FROM docker.io/library/node:16                                                                                                                                                        0.0s
 => [internal] load build context                                                                                                                                                               0.0s
 => => transferring context: 297B                                                                                                                                                               0.0s
 => CACHED [2/8] RUN apt-get update && apt-get install libvips-dev -y                                                                                                                           0.0s
 => CACHED [3/8] WORKDIR /opt/                                                                                                                                                                  0.0s
 => CACHED [4/8] COPY ./package.json ./package-lock.json ./                                                                                                                                     0.0s
 => CACHED [5/8] RUN npm install                                                                                                                                                                0.0s
 => CACHED [6/8] WORKDIR /opt/app                                                                                                                                                               0.0s
 => CACHED [7/8] COPY ./ .                                                                                                                                                                      0.0s
 => ERROR [8/8] RUN npm run build                                                                                                                                                               0.5s
------
 > [8/8] RUN npm run build:
#0 0.465 npm ERR! Missing script: "build"
#0 0.465 npm ERR! 
#0 0.465 npm ERR! To see a list of scripts, run:
#0 0.465 npm ERR!   npm run
#0 0.466 
#0 0.466 npm ERR! A complete log of this run can be found in:
#0 0.466 npm ERR!     /root/.npm/_logs/2022-07-28T10_11_26_066Z-debug-0.log
------
failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 1
```

Any idea why this is failing? 

When I do everything manually, it works fine. npm run build is there. 

Update: this is the debug log output
```

0 verbose cli /home/codeagency/.nvm/versions/node/v18.5.0/bin/node /home/codeagency/.nvm/versions/node/v18.5.0/bin/npm
1 info using npm@8.15.0
2 info using node@v18.5.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/codeagency/.nvm/versions/node/v18.5.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/codeagency/docker/strapi-v4-local/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/codeagency/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/codeagency/.nvm/versions/node/v18.5.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 5ms
19 timing npm:load:configload Completed in 5ms
20 timing npm:load:mkdirpcache Completed in 2ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm run build
23 verbose argv "run" "build"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/home/codeagency/.npm/_logs
28 verbose logfile /home/codeagency/.npm/_logs/2022-07-28T10_16_24_435Z-debug-0.log
29 timing npm:load:logFile Completed in 3ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 13ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing command:run Completed in 3ms
36 verbose stack Error: Missing script: "build"
36 verbose stack
36 verbose stack To see a list of scripts, run:
36 verbose stack   npm run
36 verbose stack     at RunScript.run (/home/codeagency/.nvm/versions/node/v18.5.0/lib/node_modules/npm/lib/commands/run-script.js:98:13)
36 verbose stack     at async module.exports (/home/codeagency/.nvm/versions/node/v18.5.0/lib/node_modules/npm/lib/cli.js:78:5)
37 verbose cwd /home/codeagency/docker/strapi-v4-local
38 verbose Linux 5.15.0-41-generic
39 verbose node v18.5.0
40 verbose npm  v8.15.0
41 error Missing script: "build"
41 error
41 error To see a list of scripts, run:
41 error   npm run
42 verbose exit 1
43 timing npm Completed in 23ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /home/codeagency/.npm/_logs/2022-07-28T10_16_24_435Z-debug-0.log
```

**Comment by codeagencybe** [comment]
Nevermind, i got everything fixed

**Comment by Eventyret** [comment]
What was the issue since you got it fixed @codeagencybe  ? :)

**Comment by diegohmac** [comment]
@codeagencybe  how did you fix that? I'm facing the same issue when trying to run `docker-compose up -d`

**Comment by Eventyret** [comment]
> @codeagencybe how did you fix that? I'm facing the same issue when trying to run `docker-compose up -d`:
> @Eventyret maybe you happen to know what it is ?



Just to let you know this was closed a few months ago.
But make sure that you run the script in your project root directory
You seem to not have a package.json nor do you have a `.env` file in your directory. 
Without those it can't build.

**Comment by diegohmac** [comment]
> 

Thank you for replying @Eventyret ! 

This is what I did: 

1 - created an empty folder
2 - ran `npx @strapi-community/dockerize` 
3 - ran `docker-compose up -d`
4 - got the build error.

I have a `.env` and `package.json` file and I'm using NPM with Node `v16.13.2`

**Comment by Eventyret** [comment]
> > 
> 
> Thank you for replying @Eventyret ! 
> 
> This is what I did: 
> 
> 1 - created an empty folder
> 2 - ran `npx @strapi-community/dockerize` 
> 3 - ran `docker-compose up -d`
> 4 - got the build error.
> 
> I have a `.env` and `package.json` file and I'm using NPM with Node `v16.13.2`

Step 1 is the project it needs to be in a strapi project folder

**Comment by diegohmac** [comment]
> > > 
> > 
> > 
> > Thank you for replying @Eventyret !
> > This is what I did:
> > 1 - created an empty folder
> > 2 - ran `npx @strapi-community/dockerize`
> > 3 - ran `docker-compose up -d`
> > 4 - got the build error.
> > I have a `.env` and `package.json` file and I'm using NPM with Node `v16.13.2`
> 
> Step 1 is the project it needs to be in a strapi project folder

Ops, you're correct! I created the project folder the way you said on the blog post and now I'm getting a different error: 

` password authentication failed for user "strapi"`

I tried changing Dockerfile to `node:14` but still the same 🤔

**Comment by Eventyret** [comment]
Need to make sure the variables exists in .env and they are the same in database.js and docker compose.

**Comment by codeagencybe** [comment]
@Eventyret the fix for my case was I was in the wrong folder. 
I got it mixed up with git which also create a folder when you clone. 
Then when you run npx command, it also creates a folder for you so I got stuff nested and confused. 

Probably you are also running the command outside your project folder and that's why it gives that error.

**Comment by diegohmac** [comment]
@Eventyret all variables exists in `.env`, `database.js` and `docker-compose.yml`. 

When I run the `docker-compose up -d` command it puts up both containers! `strapiDB` is running fine but the problem is `strapi`:

It's on a loop throwing erros saying that it was not possible to install `sharp` module:

```
Could not load js config file /opt/app/node_modules/@strapi/plugin-upload/strapi-server.js:

Something went wrong installing the "sharp" module


Cannot find module '../build/Release/sharp-linuxmusl-x64.node'

Require stack:

- /opt/app/node_modules/sharp/lib/sharp.js

- /opt/app/node_modules/sharp/lib/constructor.js

- /opt/app/node_modules/sharp/lib/index.js

- /opt/app/node_modules/@strapi/plugin-upload/server/services/image-manipulation.js

- /opt/app/node_modules/@strapi/plugin-upload/server/services/index.js

- /opt/app/node_modules/@strapi/plugin-upload/server/index.js

- /opt/app/node_modules/@strapi/plugin-upload/strapi-server.js

- /opt/app/node_modules/@strapi/strapi/lib/utils/import-default.js

- /opt/app/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js

- /opt/app/node_modules/@strapi/strapi/lib/core/app-configuration/config-loader.js

- /opt/app/node_modules/@strapi/strapi/lib/core/app-configuration/index.js

- /opt/app/node_modules/@strapi/strapi/lib/commands/develop.js

- /opt/app/node_modules/@strapi/strapi/bin/strapi.js


Possible solutions:

- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"

- Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"

- Consult the installation documentation: https://sharp.pixelplumbing.com/install
``` 

I also tried adding both of the following commands to the Dockerfile but still the same issue persists:
`RUN npm install --ignore-scripts=false --foreground-scripts --verbose sharp`
`RUN npm install --platform=linuxmusl --arch=x64 sharp`

**Comment by arndtteunissen-org** [comment]
@Eventyret Hey, sorry, but i am having the same issue. node_modules is in dockerignore and still problems with sharp. I am running Ubuntu 22.04. Strapi runs fine locally, but no matter how i try to run it in docker, it refuses to get past the sharp issue.

**Comment by Eventyret** [comment]
> @Eventyret Hey, sorry, but i am having the same issue. node_modules is in dockerignore and still problems with sharp. I am running Ubuntu 22.04. Strapi runs fine locally, but no matter how i try to run it in docker, it refuses to get past the sharp issue.

You would need to post your dockerfile, dockerignore and docker-compose please ☺️

**Comment by arndtteunissen-org** [comment]
Dockerfile:

`FROM node:16-alpine
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY package.json yarn.lock ./
RUN yarn config set network-timeout 600000 -g && yarn install

WORKDIR /opt/app
COPY . .
ENV PATH /opt/node_modules/.bin:$PATH
RUN chown -R node:node /opt/app
USER node
RUN ["yarn", "build"]
EXPOSE 1337
CMD ["yarn", "develop"]`

Dockerignore:

`.tmp/
.cache/
.git/
build/
node_modules/
.env
data/
backup/`

Docker-compose:

`version: '3'
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
      
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'
    networks:
      - strapi
      
  strapiAdminer:
    container_name: strapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=strapiDB
    networks:
      - strapi
    depends_on:
      - strapiDB

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
`

**Comment by Eventyret** [comment]
How are you building the image or using docker compose for it?

**Comment by arndtteunissen-org** [comment]
@Eventyret I am using docker compose

**Comment by Eventyret** [comment]
> @Eventyret I am using docker compose

Can you try with --force-recreate --build so it builds fresh images.

**Comment by arndtteunissen-org** [comment]
@Eventyret That fixed it! Thank you very much!
